version: '3.8'

services:
  app:
    image: node:latest
    container_name: db_practice
    ports:
      - "3000:3000"
      - "9229:9229" # for debug
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    env_file:
      - app.env
    depends_on:
      - mysql
    stdin_open: true
    tty: true
  
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - db.env

volumes:
  mysql-data:
