version: '3.8'
services:
    node-app:
        image: node:latest
        ports:
          - "3000:3000"
        volumes:
          - .:/app
        working_dir: /app
        command: node webserver.js
        tty: true
