version: '3.8'

services:
  app:
    image: node:latest
    container_name: bluesky1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    env_file:
      - app.env
    stdin_open: true
    tty: true